insert into PostalCode (PostalCode, City) values ('59500-000', 'Macau');
insert into PostalCode (PostalCode, City) values ('L-6231', 'Bech');
insert into PostalCode (PostalCode, City) values ('G8V', 'Gravelbourg');
insert into PostalCode (PostalCode, City) values ('4324', 'Pagsañgahan');
insert into PostalCode (PostalCode, City) values ('30430', 'Sida');
insert into PostalCode (PostalCode, City) values ('191017', 'Buenos Aires');
insert into PostalCode (PostalCode, City) values ('B2V', 'Catalina');
insert into PostalCode (PostalCode, City) values ('1706', 'Pulo');
insert into PostalCode (PostalCode, City) values ('35513 CEDEX', 'Cesson-Sévigné');
insert into PostalCode (PostalCode, City) values ('671633', 'Logovskoye');
