insert into PostalCode (PostalCode, City) values (null, 'Sukaraja');
insert into PostalCode (PostalCode, City) values ('L-6231', 'Bech');
insert into PostalCode (PostalCode, City) values (null, 'Gyumri');
insert into PostalCode (PostalCode, City) values (null, 'Gwio Kura');
insert into PostalCode (PostalCode, City) values ('30430', 'Sida');
insert into PostalCode (PostalCode, City) values ('191017', 'Buenos Aires');
insert into PostalCode (PostalCode, City) values (null, 'Ostružnica');
insert into PostalCode (PostalCode, City) values ('1706', 'Pulo');
insert into PostalCode (PostalCode, City) values ('35513 CEDEX', 'Cesson-Sévigné');
insert into PostalCode (PostalCode, City) values (null, 'Fanzhuang');
