insert into Restaurant (RestaurantID, Name, Email, PhoneNumber, Address) values (1, 'Kiehn-Senger', 'theenan0@bbc.co.uk', '621-393-5154', '8 1st Plaza');
insert into Restaurant (RestaurantID, Name, Email, PhoneNumber, Address) values (2, 'Brown Inc', 'onevett1@elegantthemes.com', '527-596-3891', '430 Lindbergh Road');
insert into Restaurant (RestaurantID, Name, Email, PhoneNumber, Address) values (3, 'Greenholt Group', 'cbaudet2@yahoo.co.jp', '266-256-6622', '3 Maple Wood Point');
insert into Restaurant (RestaurantID, Name, Email, PhoneNumber, Address) values (4, 'Schuster-Conn', 'rceyssen3@people.com.cn', '436-462-0171', '51780 Russell Place');
insert into Restaurant (RestaurantID, Name, Email, PhoneNumber, Address) values (5, 'Pfannerstill Group', 'rmcrae4@slate.com', '141-775-6435', '04335 Twin Pines Court');
insert into Restaurant (RestaurantID, Name, Email, PhoneNumber, Address) values (6, 'Cassin-O''Hara', 'aelwyn5@shareasale.com', '673-797-1713', '1 Blackbird Pass');
insert into Restaurant (RestaurantID, Name, Email, PhoneNumber, Address) values (7, 'Lesch-Haag', 'abrahams6@1und1.de', '756-564-2941', '6 Gina Parkway');
insert into Restaurant (RestaurantID, Name, Email, PhoneNumber, Address) values (8, 'Windler and Sons', 'arubica7@vimeo.com', '990-216-5110', '2 Sheridan Alley');
insert into Restaurant (RestaurantID, Name, Email, PhoneNumber, Address) values (9, 'Prohaska LLC', 'ncardillo8@123-reg.co.uk', '415-888-9709', '674 Kensington Place');
insert into Restaurant (RestaurantID, Name, Email, PhoneNumber, Address) values (10, 'Abernathy and Sons', 'velston9@wufoo.com', '469-216-5073', '3 Fallview Trail');
